version: '3'

networks:
  default:
    driver: bridge
    ipam:
      config:
        - subnet: 172.16.57.0/24

services:
  docker-postgres:
    image: postgres:10.4
    ports:
      - '5432:5432'
    container_name: postgresContainer
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    networks:
      - default
    restart: always