spring:
  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: postgres
  jpa:
    show_sql: true
    generate-ddl: true
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
    database-platform: org.hibernate.dialect.PostgreSQLDialect